version: '3.9'

services:
  receptacles_detection_service:
    image: 064427434392.dkr.ecr.us-east-1.amazonaws.com/receptacles_detection_service:latest
    container_name: receptacles_detection_service
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '${DEV_SYSTEM_PATH_TO_MODEL}:${DEV_DOCKER_PATH_TO_MODEL}'
      - '${DEV_SYSTEM_PATH_TO_CUDA_CACHE}:${DEV_DOCKER_PATH_TO_CUDA_CACHE}'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - ENVIRONMENT=DEVELOPMENT
    env_file:
      - .env
      - src_env/dev/.env
    ports:
      - '${DEV_SYSTEM_APP_PORT}:${DEV_APP_PORT}/tcp'
    expose:
      - '${DEV_APP_PORT}/tcp'
    networks:
      - drawer-dev
    command: gunicorn main:app --worker-tmp-dir /dev/shm -b ${DEV_APP_HOST}:${DEV_APP_PORT} -w ${DEV_APP_WORKERS} -t ${DEV_APP_TIMEOUT} --graceful-timeout $DEV_APP_GRACEFUL_TIMEOUT -k uvicorn.workers.UvicornWorker

networks:
  drawer-dev:
    driver: bridge
